hns:
  scales:
    0: 0.54
    1: 0.82
    2: 1.10
    3: 1.65
  scale-thresholds:
    1: 180
    2: 300
    3: 480
  hider-slow:
    trigger-seconds: 30
    amplifier: 5
  radar:
    mode: CHUNK
  items:
    hider:
      abatukan: true
      nail-brick: true
      whistle-1: true
      whistle-2: true
      whistle-3: true
    hunter:
      sword: true
      bow: true
      arrow: true
      pearl: true
      grenade: true
      small-firecracker: true
      radar: true
      tracking-radar: true
  random-events:
    enabled: false
    mode: RANDOM
    interval-seconds: 120
    events:
      hider-reveal: true
      hider-slow: true
      hunter-haste: true
      hider-boost: true
